TensorFlow is an open-source end to end machine learning library for preprocessing data, modeling data and serving models.


In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


In [3]:
#Create Tensor with constant
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
print('Dimension: \t',scaler.ndim)

Dimension: 	 0


In [5]:
print('Shape: \t',scaler.shape)

Shape: 	 ()


In [6]:
print('Datatype: \t',scaler.dtype)

Datatype: 	 <dtype: 'int32'>


In [8]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
print('Dimension: \t',vector.ndim)
print('Shape: \t',vector.shape)
print('Datatype: \t',vector.dtype)



Dimension: 	 1
Shape: 	 (2,)
Datatype: 	 <dtype: 'int32'>


In [11]:
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
print('Dimension: \t',matrix.ndim)
print('Shape: \t',matrix.shape)
print('Datatype: \t',matrix.dtype)


Dimension: 	 2
Shape: 	 (2, 2)
Datatype: 	 <dtype: 'int32'>


In [15]:
import numpy

In [20]:
size=tf.size(matrix)
print(size.numpy())

4


In [22]:
print('Scaler Size: ',tf.size(scaler).numpy())
print('Vector Size: ',tf.size(vector).numpy())
print('Matrix Size: ',tf.size(matrix).numpy())

Scaler Size:  1
Vector Size:  2
Matrix Size:  4
