In [7]:
import numpy as np

In [8]:
#Numpy array is called ndarray
array1=np.array([15,20,25,30,14,55,33])
print(array1)

[15 20 25 30 14 55 33]


In [9]:
print('Type of array: \t',type(array1))

Type of array: 	 <class 'numpy.ndarray'>


In [10]:
print('Dimension of Array: \t',array1.ndim)

Dimension of Array: 	 1


In [11]:
print('Shape of Array: \t',array1.shape)

Shape of Array: 	 (7,)


In [12]:
print('Size of Array',array1.size)

Size of Array 7


In [14]:
print('DataType of Array',array1.dtype)

DataType of Array int64


In [15]:
for (i,item) in enumerate(array1):
  print(i,item)

0 15
1 20
2 25
3 30
4 14
5 55
6 33


In [18]:
print(f'Total of 3rd:{array1[2]} and 4th: {array1[3]} items is: \t ',(array1[2]+array1[3]))

Total of 3rd:25 and 4th: 30 items is: 	  55


**Numpy 2D Array**

In [19]:
array2=np.array([[10,20,30,40],[240,350,450,550]])

In [21]:
print(array2)

[[ 10  20  30  40]
 [240 350 450 550]]


In [20]:
print('array2 Dimension: \t',array2.ndim)
print('array2 Shape: \t',array2.shape)
print('array2 Size: \t',array2.size)
print('array2 Data Type: \t',array2.dtype)
print('array2 Item Size: \t',array2.itemsize)

array2 Dimension: 	 2
array2 Shape: 	 (2, 4)
array2 Size: 	 8
array2 Data Type: 	 int64
array2 Item Size: 	 8


In [22]:
for i,v in np.ndenumerate(array2):
  print(i,v)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40
(1, 0) 240
(1, 1) 350
(1, 2) 450
(1, 3) 550


####NumPy can create Zero arrays in all dimension using np.zeros() with 0 values filled
* 1D Vector
* 2D Matrix
*  3D Array
* n dimensional array

In [32]:
vector_zeros=np.zeros(10,dtype=float)
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
print('Dimension: \t',vector_zeros.ndim)
print('Shape: \t',vector_zeros.shape)
print('Size: \t',vector_zeros.size)
print('Data Type: \t',vector_zeros.dtype)

Dimension: 	 1
Shape: 	 (10,)
Size: 	 10
Data Type: 	 float64


In [36]:
#numpy.zeros(shape,dtype=...)
matrix_z=np.zeros((3,4),dtype=int)
print(matrix_z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [37]:
print('Dimension: \t',matrix_z.ndim)
print('Shape: \t',matrix_z.shape)
print('Size: \t',matrix_z.size)
print('Data Type: \t',matrix_z.dtype)


Dimension: 	 2
Shape: 	 (3, 4)
Size: 	 12
Data Type: 	 int64


In [42]:
# 3D Array
arr3=np.zeros((2,3,5),dtype=int)  # block,rows,columns
print(arr3)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [43]:
print('Dimension: \t',arr3.ndim)
print('Shape: \t',arr3.shape)
print('Size: \t',arr3.size)
print('Data Type: \t',arr3.dtype)

Dimension: 	 3
Shape: 	 (2, 3, 5)
Size: 	 30
Data Type: 	 int64


In [46]:
arr4=np.zeros((2,3,4,5),dtype=int)
print(arr4)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]


In [45]:
print('Dimension: \t',arr4.ndim)
print('Shape: \t',arr4.shape)
print('Size: \t',arr4.size)
print('Data Type: \t',arr4.dtype)

Dimension: 	 4
Shape: 	 (2, 3, 4, 5)
Size: 	 120
Data Type: 	 int64


####NumPy can creat arrays in all dimension using np.ones() with values filled by 1

In [48]:
# 1 D
arr_ones=np.ones(5,dtype=int)
print(arr_ones)

[1 1 1 1 1]


In [49]:
print('Dimension: \t',arr_ones.ndim)
print('Shape: \t',arr_ones.shape)
print('Size: \t',arr_ones.size)
print('Data Type: \t',arr_ones.dtype)

Dimension: 	 1
Shape: 	 (5,)
Size: 	 5
Data Type: 	 int64


In [50]:
arr_2=np.ones((2,3),dtype=int)
print(arr_2)

[[1 1 1]
 [1 1 1]]


In [51]:
print('Dimension: \t',arr_2.ndim)
print('Shape: \t',arr_2.shape)
print('Size: \t',arr_2.size)
print('Data Type: \t',arr_2.dtype)

Dimension: 	 2
Shape: 	 (2, 3)
Size: 	 6
Data Type: 	 int64


In [54]:
arr3=np.ones((2,3,5),dtype=int)  # block,rows,columns
print(arr3)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [53]:
print('Dimension: \t',arr3.ndim)
print('Shape: \t',arr3.shape)
print('Size: \t',arr3.size)


Dimension: 	 3
Shape: 	 (2, 3, 5)
Size: 	 30


In [56]:
arr4=np.ones((2,3,4,5),dtype=int)
print(arr4)

[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]]


In [55]:
print('Dimension: \t',arr4.ndim)
print('Shape: \t',arr4.shape)
print('Size: \t',arr4.size)
print('Data Type: \t',arr4.dtype)

Dimension: 	 4
Shape: 	 (2, 3, 4, 5)
Size: 	 120
Data Type: 	 int64


In [62]:
arr4=np.ones((2,3,4,5),dtype=int)*15
print(arr4)

[[[[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]]


 [[[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]]]


In [63]:
print('Dimension: \t',arr4.ndim)
print('Shape: \t',arr4.shape)
print('Size: \t',arr4.size)

Dimension: 	 4
Shape: 	 (2, 3, 4, 5)
Size: 	 120


In [64]:
array_constant=np.full((2,3,4,5),15)
print(array_constant)

[[[[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]]


 [[[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]]]


In [65]:
print('Dimension: \t',array_constant.ndim)
print('Shape: \t',array_constant.shape)
print('Size: \t',array_constant.size)
print('Data Type: \t',array_constant.dtype)

Dimension: 	 4
Shape: 	 (2, 3, 4, 5)
Size: 	 120
Data Type: 	 int64


In [73]:
#how to assign random values to numpy array
array_random=np.random.rand(4,3,2)
print(array_random)

[[[0.10164886 0.79188587]
  [0.3501941  0.44186832]
  [0.10179701 0.5974452 ]]

 [[0.6024083  0.09212894]
  [0.3187849  0.24384566]
  [0.84254728 0.57083902]]

 [[0.72682163 0.73887494]
  [0.08001903 0.28002758]
  [0.72774604 0.71381554]]

 [[0.12133697 0.93473617]
  [0.93237351 0.56188812]
  [0.11115165 0.7071409 ]]]


In [74]:
print('Dimension ',array_random.ndim)
print('Shape ',array_random.shape)
print('Size ',array_random.size)
print('Data Type ',array_random.dtype)

Dimension  3
Shape  (4, 3, 2)
Size  24
Data Type  float64


In [75]:
for index, value in np.ndenumerate(array_random):
    print(index, value)
#

(0, 0, 0) 0.10164886038323662
(0, 0, 1) 0.7918858724173373
(0, 1, 0) 0.35019410232174075
(0, 1, 1) 0.44186832399605325
(0, 2, 0) 0.10179701366524863
(0, 2, 1) 0.5974451982842768
(1, 0, 0) 0.6024083020237863
(1, 0, 1) 0.0921289435455801
(1, 1, 0) 0.31878489802077103
(1, 1, 1) 0.24384565877002684
(1, 2, 0) 0.8425472804593523
(1, 2, 1) 0.5708390164116475
(2, 0, 0) 0.7268216258665
(2, 0, 1) 0.7388749359934816
(2, 1, 0) 0.08001902630388003
(2, 1, 1) 0.28002758110327375
(2, 2, 0) 0.7277460439450623
(2, 2, 1) 0.7138155364149246
(3, 0, 0) 0.12133697165603619
(3, 0, 1) 0.9347361724529188
(3, 1, 0) 0.9323735058727476
(3, 1, 1) 0.561888120395803
(3, 2, 0) 0.11115165134707061
(3, 2, 1) 0.7071408977448456
