In [1]:
import numpy as np

In [10]:
#Mathematicl operations on numpy arrays
array_one=np.array([1,2,3,4])
array_two=np.array([5,6,7,8])
print(array_one)
print(array_two)

[1 2 3 4]
[5 6 7 8]


In [11]:
print(array_one+array_two)

[ 6  8 10 12]


In [12]:
print(array_one-array_two)

[-4 -4 -4 -4]


In [13]:
print(array_two-array_one)

[4 4 4 4]


In [14]:
print(array_one*array_two)

[ 5 12 21 32]


In [19]:
print(array_one/array_two)

[0.2        0.33333333 0.42857143 0.5       ]


In [20]:
print(array_one)
print(array_two)
array_one_two=np.concatenate([array_one,array_two])
print(array_one_two)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


In [29]:
ar1=np.array([10,20,20,5])
ar2=np.array([30,40,50,78,90,90])
ar3=np.array([60,70,80,90,100,120])
ar4=np.concatenate([ar1,ar2,ar3])
print(ar4)
print(ar4.shape)


[ 10  20  20   5  30  40  50  78  90  90  60  70  80  90 100 120]
(16,)


In [30]:
#Numpy Array Spilt
print(ar4)
ar4_split=np.array_split(ar4,3)
print(ar4_split)

[ 10  20  20   5  30  40  50  78  90  90  60  70  80  90 100 120]
[array([10, 20, 20,  5, 30, 40]), array([50, 78, 90, 90, 60]), array([ 70,  80,  90, 100, 120])]


In [32]:
spilpt_4=np.array_split(ar4,4)
print(spilpt_4)

[array([10, 20, 20,  5]), array([30, 40, 50, 78]), array([90, 90, 60, 70]), array([ 80,  90, 100, 120])]


In [34]:
array2D=np.array([
    [1,2,3],
    [100,200,500],
    [9,10,11]
])
print(array2D)

[[  1   2   3]
 [100 200 500]
 [  9  10  11]]


In [36]:
rows=np.split(array2D,3)
print(rows)

[array([[1, 2, 3]]), array([[100, 200, 500]]), array([[ 9, 10, 11]])]


In [38]:
data=np.arange(1,51)
print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [45]:
train,test=np.split(data,[40])
print(train)
print(test)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]


In [41]:
myarray=np.array([400,10,5,4,360,70,80,90,100,120])
print(myarray)
print(myarray.size)

[400  10   5   4 360  70  80  90 100 120]
10


In [46]:
train,test=np.split(myarray,[7])
print(train)
print(test)
#

[400  10   5   4 360  70  80]
[ 90 100 120]


In [47]:
print(myarray)

[400  10   5   4 360  70  80  90 100 120]


In [49]:
#Sorting of NumPy array
my_sort_array=np.sort(myarray)
print(my_sort_array)


[  4   5  10  70  80  90 100 120 360 400]


In [50]:
#Array of All items less than 20
array_less_than_20=my_sort_array[my_sort_array<20]
print(array_less_than_20)

[ 4  5 10]


In [51]:
# Array of All items greater than 100
array_greater_than_100=my_sort_array[my_sort_array>100]
print(array_greater_than_100)
#

[120 360 400]


In [52]:
# array of items excluding 10 and 100
array_excluding_10_100=my_sort_array[(my_sort_array!=10) &(my_sort_array!=100)]
print(array_excluding_10_100)

[  4   5  70  80  90 120 360 400]


In [55]:
# array greater than 10 and less than 100
array_greater_than_10_less_than_100=my_sort_array[(my_sort_array>10) & (my_sort_array<100)]
print(array_greater_than_10_less_than_100)
#

[70 80 90]


**Create a NumPy array for following Numbers**

*  10,12,13,45,67,89,91,100,23
* sort the array in ascending order of numbers
* find out all odd numbers using filter like above

**Statistical Operantions**
* sum,mean,max,min....

In [56]:
our_array=np.array([5,10,15,20,25])
print(our_array)

[ 5 10 15 20 25]


In [57]:
# Total of numbers
total=np.sum(our_array)
print(total)
#

75


In [58]:
#Average of numbers
average=np.mean(our_array)
print(average)
#

15.0


In [59]:
#Minimum
minimum=np.min(our_array)
print(minimum)

5


In [60]:
#Maximum
maximum=np.max(our_array)
print(maximum)

25


In [61]:
#Standard Devition
std_div=np.std(our_array)
print(std_div)

7.0710678118654755


In [62]:
print('Minimum from my array: ',np.min(myarray))
print('Maximum from my array: ',np.max(myarray))
print('Average from my array: ',np.mean(myarray))
print('Standard Deviation from my array: ',np.std(myarray))
print('Median from my array: ',np.median(myarray))
print('Variance from my array: ',np.var(myarray))
print('Sum from my array: ',np.sum(myarray))


Minimum from my array:  4
Maximum from my array:  400
Average from my array:  123.9
Standard Deviation from my array:  134.17484861180205
Median from my array:  85.0
Variance from my array:  18002.89
Sum from my array:  1239


In [64]:
temp_kl=np.array([35,35,28,35,27,29,34,33,25,32,28,26,25,25,24,24,25,30,24,26,32,25,23,32,25,24,28,24,25,30
])
print(temp_kl)

[35 35 28 35 27 29 34 33 25 32 28 26 25 25 24 24 25 30 24 26 32 25 23 32
 25 24 28 24 25 30]


In [65]:
print('Size: \t',temp_kl.size)

Size: 	 30


In [69]:
#Average temp. of kuala lumpur in last 30 days
#shortcut to open charmap Window + .
average_temp=np.mean(temp_kl)
print(f'Average temperature in KL: {round(average_temp,2)} °C')
#

Average temperature in KL: 27.93 °C


In [70]:
#Maximum temp
max_temp=np.max(temp_kl)
print(f'Maximum temperature in KL: {max_temp} °C')

Maximum temperature in KL: 35 °C


In [71]:
#Minimum Temp
min_temp=np.min(temp_kl)
print(f'Minimum temperature in KL: {min_temp} °C')

Minimum temperature in KL: 23 °C


In [74]:
hot_days=temp_kl[temp_kl>30]
print(f'Hot days: {hot_days}')


Hot days: [35 35 35 34 33 32 32 32]


In [75]:
print(f'Hot Days {hot_days.size} are following')
for day in hot_days:
  print(f'{day}°C', end='\t')

Hot Days 8 are following
35°C	35°C	35°C	34°C	33°C	32°C	32°C	32°C	

In [76]:
cool_days=temp_kl[temp_kl<25]
print(f'Number of Cool Days {cool_days.size},Days are as follows')
for day in cool_days:
  print(f'{day}°C', end='\t')

Number of Cool Days 6,Days are as follows
24°C	24°C	24°C	23°C	24°C	24°C	

In [78]:
steps_data=np.array([2500,4200,8000,12000,15000,300,9500,11000])
print(steps_data)

[ 2500  4200  8000 12000 15000   300  9500 11000]


### Above is a gym records of daily steps count of its members in NumPy array
* Filter and display members who walked between 5000 and 10000 stpes
* Count number of members in this range
* find the average steps of all members



In [87]:
students_marks=np.array(
    [
        [90,80,80,80,80,90],
        [90,71,86,90,75,90],
        [98,88,86,90,89,90],
        [88,82,86,91,85,76],
        [68,81,82,90,71,75],

    ]
)

# * Herea Each Row=One Student
# Each Column =marks in Subject
# We have 5 Students record in 6 subject

In [88]:
print(students_marks)

[[90 80 80 80 80 90]
 [90 71 86 90 75 90]
 [98 88 86 90 89 90]
 [88 82 86 91 85 76]
 [68 81 82 90 71 75]]


In [89]:
print('Shape of student_marks',students_marks.shape)


Shape of student_marks (5, 6)


In [98]:
student_total_marks=np.sum(students_marks,axis=1)
print('Total marks of each student:')
print(student_total_marks)
#

Total marks of each student:
[500 502 541 508 467]


In [93]:
# Find out highest marks in each subject
highest_marks_in_subject=np.max(students_marks,axis=0)
print('Highest marks in each subjcets:')
print(highest_marks_in_subject)

Highest marks in each subjcets:
[98 88 86 91 89 90]


In [94]:
lowest_marks_in_subject=np.min(students_marks,axis=0)
print('Min marks in each subjcets:')
print(lowest_marks_in_subject)

Min marks in each subjcets:
[68 71 80 80 71 75]


In [99]:
student_total_marks=np.sum(students_marks,axis=1)
print('Total marks of each student:')
print(student_total_marks)

Total marks of each student:
[500 502 541 508 467]


In [100]:
top_student=np.max(student_total_marks)
print('Top Student: ',top_student)
#

Top Student:  541
